coopersystem/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.contrib.auth import views as auth_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from core.api import viewsets
from core.views import  login_api
from core import urls as core_urls

route = routers.DefaultRouter()

route.register(r'products',viewsets.ProductViewSet, basename="Products")
route.register(r'orders',viewsets.OrderViewSet, basename="Orders")

urlpatterns = [
    # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('admin/', admin.site.urls),
    path('drf_api/', include(route.urls)),
    path('', include(core_urls)),

    ### Login by api form ###
	path('login/', login_api, 
		name="login_api_view"),
        
    ##Traditional login##
    path('login2/', auth_views.LoginView.as_view(template_name='login.html',
         redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), 
        name='logout'),
]

core/urls.py
from django.urls import path
from knox import views as knox_views

from core import views, api_views

urlpatterns = [

	### Login ###
	path('api/register/', 
		api_views.RegisterAPI.as_view(), 
		name='register'),
	path('api/login/', api_views.LoginAPI.as_view(),
		name='login_api'),
    path('api/logout/', knox_views.LogoutView.as_view(), 
		name='logout_api'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), 
		name='logoutall_api'),

	### API VIEWS ###
    
	path('urls', api_views.api_overview, 
		name="api-overview"),
	path('product-list/', 
		api_views.api_product_list, 
		name="product-list"),
	path('product-detail/<str:pk>/', 
		api_views.api_product_detail, 
		name="product-detail"),
	path('product-create/', 
		api_views.api_product_create, 
		name="product-create"),

	path('product-update/<str:pk>/', 
		api_views.api_product_update, 
		name="product-update"),
	path('product-delete/<str:pk>/', 
		api_views.api_product_delete, 
		name="product-delete"),

	### VIEWS ###

	path('', views.index, name="index"),
	
	path('product_list/', 
        views.product_list, 
		name='product_list'),
	
	path('product_create/', 
        views.product_create, 
		name='product_create'),
	
	path('product_update/<int:pk>/', 
        views.product_update, 
		name='product_update'),
	
	path('product_delete/<int:pk>/', 
        views.product_delete, 
		name='product_delete'),
	
	path('order_list/', 
        views.order_list, 
        name='order_list'),
	
	path('order_create/<int:product_pk>/',
        views.order_create,
		name='order_create'),

	path('order_detail/<int:pk>/',
        views.order_detail,
		name='order_detail'),

	path('order_update/<int:pk>/',
        views.order_update,
		name='order_update'),
	
	path('order_delete/<int:pk>/', 
        views.order_delete, 
		name='order_delete'),
	
	path('order_send/<int:pk>/', 
        views.order_send, 
		name='order_send'),
	
	path('order_delivered/<int:pk>/', 
        views.order_delivered, 
		name='order_delivered'),
	
]

core/models.py
from itertools import product
from termios import VEOL
from django.db import models

from core.custom_validators import validate_interval, validate_situation

INDISPONIVEL = 0
DISPONIVEL = 1

PENDENTE = 0
ENVIADO = 1
ENTREGUE = 2

PRODUCT_SITUATION = {
    INDISPONIVEL :'Indisponível',
    DISPONIVEL:'Disponível'
}

ORDER_SITUATION = {
    PENDENTE :'Pendente de envio',
    ENVIADO:'Enviado',
    ENTREGUE:'Entregue',
}

class Product(models.Model):
    name = models.CharField(max_length=253)
    value = models.FloatField(validators=[validate_interval])
    quantity = models.FloatField(validators=[validate_interval])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        """Product head representation"""
        return str(self.name)
    
    def get_situation(self):
        """Product situation"""
        return DISPONIVEL if self.quantity > 0 else INDISPONIVEL
    
    def get_situation_display(self):
        """Product situation"""
        sit = DISPONIVEL if self.quantity > 0 else INDISPONIVEL
        return PRODUCT_SITUATION[sit]
    
    def field_list(self):
        return [
                (u'Cod', self.pk),
                (u'Nome', self.name),
                (u'Valor unitário', u"R$ %.2f"%(self.value)),
                (u'Quantidade', self.quantity),
                ]

class Order(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    value = models.FloatField(validators=[validate_interval])
    quantity = models.FloatField(validators=[validate_interval])
    requester = models.CharField(max_length=253)
    zip_code = models.CharField(max_length=9)
    city = models.CharField(max_length=253)
    address = models.CharField(max_length=253)
    district = models.CharField(max_length=253)
    number = models.PositiveIntegerField()
    dispatcher = models.CharField(max_length=253)
    situation = models.PositiveIntegerField(validators=[validate_interval], 
                default=PENDENTE)
    created_at = models.DateTimeField(auto_now_add=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    received_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        """Order head representation"""
        return str(self.pk)
    
    def get_situation_display(self):
        """Order situation"""
        return ORDER_SITUATION[self.situation]
    
    def get_next_situation(self):
        """Next order situation from current situation"""
        if self.situation < ENTREGUE:
            return self.situation+1
        return self.situation
    
    def get_unitary_value(self):
        """Unitary value from order"""
        return self.value/self.quantity
    
    def field_list(self):
        return [
                (u'Cod', self.pk),
                (u'Data Pedido', self.created_at),
                (u'Produto', self.product),
                (u'Valor Pedido', u"R$ %.2f"%(self.value)),
                (u'Quantidade', self.quantity),
                (u'Valor Unitário', u"R$ %.2f"%(self.get_unitary_value())),
                ]

core/views.py
import json
from multiprocessing import context
from urllib import request
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction
from django.contrib import messages
from rest_framework.renderers import JSONRenderer
from datetime import datetime
from core.forms import OrderEditForm, OrderForm, ProductForm, ProductUpdateForm

from core.models import ENTREGUE, ENVIADO, PENDENTE, Product, Order

def login_api(request):
	return render(request, 'login_api.html')

@login_required
def index(request):
	return render(request, 'base.html')

@login_required
def product_list(request):
    products = Product.objects.all().order_by('-created_at')
    
    form = ProductForm()
    context = {'object_list': products,
                'title':'Produtos',
                'form':form,
                'action':'/product_create/'
                }
    return render(request, 'product_list.html', context )

@login_required
@csrf_exempt
def product_create(request):
    form = ProductForm( request.POST or None)
    if request.method =="POST":
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                'Produto criado com sucesso.')
            return HttpResponseRedirect(reverse_lazy('product_list'))
    else:
        context = {
                    'form':form,
                    'action':'/product_create/',
                    'title':'Produtos',
                    }
    return render(request, 'product_list.html', context)

@login_required
@csrf_exempt
def product_update(request,pk):
    object = get_object_or_404(Product,pk=pk)
    form = ProductUpdateForm( request.POST or None, instance=object)
    if request.method =="POST":
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                'Produto editado com sucesso.')
            return HttpResponseRedirect(reverse_lazy('product_list'))
    else:
        context = {
                    'form':form,
                    'action':'/product_update/%d/'%(pk),
                    'title':'Produtos',
                    }
    return render(request, 'product_list.html', context)

@login_required
@csrf_exempt
def product_delete(request,pk):
    object = get_object_or_404(Product,pk=pk)
    form = ProductUpdateForm( request.POST or None, instance=object)
    if request.method =="POST":
        object.delete()
        messages.add_message(request, messages.SUCCESS,
                            'Produto Deletado com sucesso.')
        return HttpResponseRedirect(reverse_lazy('product_list'))
    else:
        context = {
                    'form':form,
                    'action':'/product_delete/%d/'%(pk),
                    'title':'Produtos',
                    }
    return render(request, 'product_list.html', context)

@login_required
@csrf_exempt
def order_create(request,product_pk):
    product = get_object_or_404(Product,pk=product_pk)
    form = OrderForm(product, request.POST or None, initial={'product':product})
    if request.method =="POST":
        if form.is_valid():
            order = form.save(commit=False)
            order.value = product.value*order.quantity
            order.save()
            product.quantity -= order.quantity
            product.save()
            messages.add_message(request, messages.SUCCESS,
                                'Pedido criado com sucesso.')
            return HttpResponseRedirect(reverse_lazy('order_list'))
    
    if product.quantity > 0:
            messages.add_message(request, messages.INFO,
                            'Atenção! Somente %d itens disponíveis!'%(product.quantity))
    else:
        messages.add_message(request, messages.ERROR,
                            'Produto indisponível no momento!')
    context = {
                'form':form,
                'action':'/order_create/%d/'%(product_pk),
                'title':'Pedidos',
                }
    return render(request, 'order_list.html', context)

@login_required
def order_detail(request,pk):
    order = get_object_or_404(Order,pk=pk)
    context = {
                'order':order,
                'action':'/product_delete/%d/'%(pk),
                'title':'Detalhes do Pedido %d'%(pk),
                }
    return render(request, 'order_detail.html', context)

@login_required
@csrf_exempt
def order_update(request,pk):
    order = get_object_or_404(Order,pk=pk)
    product = get_object_or_404(Product,pk=order.product.pk)
    form = OrderEditForm(request.POST or None,instance=order)
    if request.method =="POST" and order.situation == PENDENTE:
        before_quantity = order.quantity
        if form.is_valid():
            order = form.save(commit=False)
            order.value = product.value*order.quantity
            order.save()
            if order.quantity > before_quantity:
                product.quantity -= (order.quantity-before_quantity)
            else:
                product.quantity += (before_quantity - order.quantity)
            product.save()
            messages.add_message(request, messages.SUCCESS,
                                'Pedido editado com sucesso.')
            return HttpResponseRedirect(reverse_lazy('order_list'))
    
    if product.quantity > 0:
            messages.add_message(request, messages.INFO,
                            'Atenção! Somente %d itens disponíveis!'%(product.quantity))
    else:
        messages.add_message(request, messages.ERROR,
                            'Produto indisponível no momento!')
    if order.situation > PENDENTE:
        messages.add_message(request, messages.ERROR,
                            'Não é possível editar pedidos enviados ou recebidos!')
    context = {
                'form':form,
                'action':'/order_update/%d/'%(pk),
                'title':'Pedidos',
                }
    return render(request, 'order_list.html', context)

@login_required
def order_list(request):

    orders = Order.objects.all().order_by('-created_at')

    context = {
        'object_list': orders,
        'title':'Pedidos',
        'action':'/order_create/'
        }
    
    #return HttpResponse(orders)

    return render(request, 'order_list.html', context)

@login_required
@csrf_exempt
def order_delete(request,pk):
    order = get_object_or_404(Order,pk=pk)
    if request.method =="POST" and order.situation == PENDENTE:
        product = order.product
        product.quantity += order.quantity
        product.save()
        order.delete()
        messages.add_message(request, messages.SUCCESS,
                            'Pedido deletado com sucesso. Produtos voltaram ao estoque')
        return HttpResponseRedirect(reverse_lazy('order_list'))
    else:
        if order.situation > PENDENTE:
            messages.add_message(request, messages.ERROR,
                            'Não é possível excluir pedidos enviados ou recebidos!')
        context = {
                    'action':'/order_delete/%d/'%(pk),
                    'title':'Pedidos',
                    }
    return render(request, 'order_list.html', context)


@login_required
@csrf_exempt
def order_send(request,pk):
    order = get_object_or_404(Order,pk=pk)
    if request.method =="POST" and order.situation == PENDENTE:
        order.situation = ENVIADO
        order.sent_at = datetime.now()
        order.save()
        messages.add_message(request, messages.SUCCESS,
                            'Pedido enviado com sucesso!')
        return HttpResponseRedirect(reverse_lazy('order_list'))
    else:
        if order.situation > PENDENTE:
            messages.add_message(request, messages.ERROR,
                            'Pedido já foi enviado ou recebido!')
        context = {
                    'title':'Pedidos',
                    }
    return render(request, 'order_list.html', context)


@login_required
@csrf_exempt
def order_delivered(request,pk):
    order = get_object_or_404(Order,pk=pk)
    if request.method =="POST" and order.situation == ENVIADO:
        order.situation = ENTREGUE
        order.received_at = datetime.now()
        order.save()
        messages.add_message(request, messages.SUCCESS,
                            'Pedido entregue com sucesso!')
        return HttpResponseRedirect(reverse_lazy('order_list'))
    else:
        if order.situation > ENVIADO:
            messages.add_message(request, messages.ERROR,
                            'Pedido já foi enviado ou recebido!')
        context = {
                    'title':'Pedidos',
                    }
    return render(request, 'order_list.html', context)

core/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>Coopersystem</title>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700'
              rel='stylesheet'
              type='text/css'>
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-6 text-center mb-5"></div>
                </div>
            </div>
            <div class="container">
                <nav class="navbar navbar-expand-lg ftco_navbar ftco-navbar-light"
                     id="ftco-navbar">
                    <div class="container">
                        <a class="navbar-brand" href="#">
                            <img class="ml-10"
                                 src="{% static 'img/logo_coopersystem.png' %}"
                                 height="50"
                                 alt="Coopersystem">
                        </a>
                        <button class="navbar-toggler"
                                type="button"
                                data-toggle="collapse"
                                data-target="#ftco-nav"
                                aria-controls="ftco-nav"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="fa fa-bars"></span> Menu
                        </button>
                        <div class="collapse navbar-collapse" id="ftco-nav">
                            <ul class="navbar-nav ml-auto mr-md-3">
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="/">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="/drf_api">APIs REST</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'product_list' %}">Produtos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'order_list' %}">Pedidos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'swagger-ui' %}">Swagger</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'redoc' %}">Redoc</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"href="{% url 'logout' %}">Sair</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="container">
                <h4 class="h4">{% block content-title %}Bem-vindo, {{ user.username }} {% endblock %}</h4>
                {% block content %}
                <h4>Teste Técnico Coopersystem</h4>
                {% endblock %}
            </div>
        </section>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/feather.min.js' %}"></script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block extra-js %}{% endblock %}
    </body>
</html>

core/templates/generic_list.html
{% extends "base.html" %}

{% block content-title %}
{{title}}
{% endblock %}

{% block content %}

<br/>   
<form class="form" method="post">
    {% csrf_token %}
    <div class="row">
        {% bootstrap_form form layout='inline' %}
        <div class="col">
            <button type="submit" class="btn btn-primary">
                Consultar API
            </button>
        </div>
    </div>
</form>
<br/>
{%  if object_list %}
<table class="table table-striped">
    {% for obj in object_list %}
        {% if forloop.first %}
        <thead>
            <tr>
                {% for label, value in obj.field_list %}
                <th>{{label}}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
        {% endif %}
            <tr>
                {% for label, value in obj.field_list %}
                <td><a>{{value}}</a></td>
                {% endfor %}
            </tr>
            {% if forloop.last %}
        </tbody>
        <tfoot>
            <tr>
                {% for label, value in obj.field_list %}
                <th>{{label}}</th>
                {% endfor %}
            </tr>
        </tfoot>
        {% endif %}
    {% endfor %}
</table>
{% endif %}
{% endblock %}

core/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">
    <main class="form-signin">
        <form method="post">
            {% csrf_token %}

            {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
            <h3>Autenticação</h3>
            <div class="form-floating">
                <input type="username" class="form-control" name="username" id="username" placeholder="usuário">
                <label for="username">Usuário</label>
            </div>
            <br/>
            <div class="form-floating">
                <input type="password" class="form-control" name="password" id="password" placeholder="senha">
                <label for="password">Senha</label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
        </form>
    </main>
</body>
</html>

core/templates/login_api.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">
    <main class="form-signin">
        <form id="formLogin" method="post">
            <h3>Autenticação</h3>
            <div class="form-floating">
                <input type="username" class="form-control" name="username" id="username" placeholder="usuário">
                <label for="username">Usuário</label>
            </div>
            <br/>
            <div class="form-floating">
                <input type="password" class="form-control" name="password" id="password" placeholder="senha">
                <label for="password">Senha</label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
        </form>
        <br/><div id="decoded"></div>
    </main>
</body>

<script>
    formLogin.onsubmit = async (e) => {
      e.preventDefault();
      var form = document.querySelector("#formLogin");

        data = {
            username : form.querySelector('input[name="password"]').value,
            password : form.querySelector('input[name="password"]').value,
        }

        let response = await fetch('http://localhost:8000/api/login/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
        })

        let status = await response.status;
        if (status == '200') {
            window.location.href = "http://localhost:8000/";
        }
        else {
            document.querySelector("#decoded").innerHTML = "Credenciais inválidas!"
        }
            
    };
</script>
</html>

core/templates/order_list.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% block content-title %}
{{title}}
{% endblock %}

{% block content %}

{% bootstrap_messages %}  
{%  if form %}
<form class="form" method="post" action={{action}}>
    {% csrf_token %}
    <div class="row">
        {% for field in form %}
        {% bootstrap_field field show_label=False %}
        {% endfor %}
        <div class="col">
            <button type="submit" class="btn btn-primary">
                Salvar
            </button>
            <input type="button" class="btn btn-primary" value="Voltar" onClick="history.go(-1)">
        </div>
    </div>
</form>
<br/>
{%  endif %}
{%  if object_list %}
<table class="table table-striped">
    {% for obj in object_list %}
        {% if forloop.first %}
        <thead>
            <tr>
                {% for label, value in obj.field_list %}
                <th>{{label}}</th>
                {% endfor %}
                <th><a>Situação</a></th>
                <th><a>Editar</a></th>
                <th><a>Excluir</a></th>
                <th><a>Ação</a></th>
            </tr>
        </thead>
        <tbody>
        {% endif %}
            <tr>
                {% for label, value in obj.field_list %}
                <td><a href="{% url 'order_detail' obj.pk %}">{{value}}</a></td>
                {% endfor %}
                <td>
                    <a class="{% if obj.situation == 2 %} btn btn-success btn-sm {% elif obj.situation == 1 %} btn btn-info btn-sm {% else %} btn btn-warning btn-sm {% endif %}"  role="button">{{obj.get_situation_display}}</a>
                </td>

                <td>{% if obj.situation == 0 %}
                    <a class="btn btn-outline-warning btn-sm" href="{% url 'order_update' obj.pk %}" role="button">Editar</a>
                    {% endif %}
                </td>

                <td>{% if obj.situation == 0 %}
                    <form name='delete_form' action="{% url 'order_delete' obj.id %}" method='POST' onclick="return deletechecked()"> {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger btn-sm">Excluir</button>
                    </form>
                    {% endif %}
                </td>
                <td>
                    {% if obj.situation == 0 %}
                    <form name='act_form' action="{% url 'order_send' obj.pk %}" method='POST' onclick="return sendchecked()"> {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-sm">Enviar Pedido</button>
                    </form>
                    {% elif obj.situation == 1 %}
                    <form name='act_form' action="{% url 'order_delivered' obj.pk %}" method='POST' onclick="return deliveredchecked()"> {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-sm">Receber Pedido</button>
                    </form>
                    {% endif %}
                   
                </td>
            </tr>
            {% if forloop.last %}
        </tbody>
        <tfoot>
            <tr>
                {% for label, value in obj.field_list %}
                <th>{{label}}</th>
                {% endfor %}
                <th><a>Situação</a></th>
                <th><a>Editar</a></th>
                <th><a>Excluir</a></th>
                <th><a>Ação</a></th>
            </tr>
        </tfoot>
        {% endif %}
    {% endfor %}
</table>
{% endif %}
{% endblock %}

{% block extra-js %}
<script type="text/javascript" > 
    function deletechecked()
    {
        var answer = "Realmente deseja excluir ?";
        if (confirm(answer)){
         document.delete_form.submit();
        }
        return false;  
    }
</script>
<script type="text/javascript" > 
    function sendchecked()
    {
        var answer = "Realmente deseja enviar o pedido ?";
        if (confirm(answer)){
         document.send_form.submit();
        }
        return false;  
    }
</script>
<script type="text/javascript" > 
    function deliveredchecked()
    {
        var answer = "Você confirma o recebimento do o pedido ?";
        if (confirm(answer)){
         document.received_form.submit();
        }
        return false;  
    }
</script>

<script>
    $(document).ready(function(){
        $("#id_zip_code").focusout(function(){
  
            var cep = $("#id_zip_code").val().replace(/\D/g, '');
        
            if (cep != "") {
        
                var validacep = /^[0-9]{8}$/;
        
                if(validacep.test(cep)) {
        
                $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {
        
                        if (!("erro" in dados)) {
                            $("#id_address").val(dados.logradouro);
                            $("#id_district").val(dados.bairro);
                            $("#id_city").val(dados.localidade);
                        } //end if.
                        else {
                            console.log("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    console.log("Formato de CEP inválido.");
                }
            } //end if.
          });
        });
</script>
{% endblock %}